### ISSUE TITLE
Backtest failing when strategy name has '-' in it's name

### ISSUE THREAD

**Issue by H256** [xFFFFF/Gekko-BacktestTool#12]
Hi, there - first of all : Great tool! :)

However I noticed, that the Backtest is failing when strategies have the minus-sign in their name:

```
F:\workspace\gekko-stuff\gekko\tmp\tmp_configVQbdM.js:27
config.tether-simple = {
^^^^^^^^^^^^^^^^^^^^

ReferenceError: Invalid left-hand side in assignment
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.getConfig (F:\workspace\gekko-stuff\gekko\core\util.js:46:15)
```
Maybe it's better if the script would generate the following assignment statement: 
`config["tether-simple"] = { .... }`

**Comment by xFFFFF** [comment]
Nice trick! I will implement it in new version. Thanks! :)
