### ISSUE TITLE
Backtest fails to run with multiple parameter ranges in toml

### ISSUE THREAD

**Issue by WilbertNL** [xFFFFF/Gekko-BacktestTool#54]
Hi,

When I change one parameter in the .toml to a range like:
`SMA_long = "210..215:1"`
`SMA_short = 20` 
all goes well, but as soon as I add another one like:
`SMA_long = "210..215:1"`
`SMA_short = "10..13:1"`
I get errors:

```
/home/gekkoadmin/gekko/core/tulind.js:42
            throw new Error(tulindError + paramName + ' needs to be a number');
            ^

Error: Gekko was unable to configure Tulip Indicators:
	optInTimePeriod needs to be a number
    at _.each.paramName (/home/gekkoadmin/gekko/core/tulind.js:42:19)
    at Function.forEach (/home/gekkoadmin/gekko/node_modules/lodash/dist/lodash.js:3298:15)
    at verifyParams (/home/gekkoadmin/gekko/core/tulind.js:34:7)
    at Object.create (/home/gekkoadmin/gekko/core/tulind.js:696:9)
    at AsyncIndicatorRunner.addTulipIndicator (/home/gekkoadmin/gekko/plugins/tradingAdvisor/asyncIndicatorRunner.js:145:23)
    at Base.addTulipIndicator (/home/gekkoadmin/gekko/plugins/tradingAdvisor/baseTradingMethod.js:226:29)
    at Base.bound [as addTulipIndicator] (/home/gekkoadmin/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Base.init (/home/gekkoadmin/gekko/strategies/RSI_BULL_BEAR_ADX.js:34:8)
    at Base.bound [as init] (/home/gekkoadmin/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at new Base (/home/gekkoadmin/gekko/plugins/tradingAdvisor/baseTradingMethod.js:69:8)
USDT-BTC Backtest is failed. 
```

It doesn't matter which parameter is put in a test-range; as long as it is one it works, but as soon as a second is added it fails.

BacktestTool v0.7
Gekko v0.6.8

I had to make to manual changes to the backtest.pl file:
- one because of the 0.0% profit reporting #35 
- one because of the exchange/ addition #45 

Any help would be greatly appreciated, thanks!

EDIT: cleaned up layout of output

**Comment by dannycoin** [comment]
> cleaned up layout of output

did you find a solution?
